import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/css/globals.css'
import QueryProvider from '@/app/provider'
import Navbar from '@/component/navbar'
import ScrollToTop from '@/component/scroll-to-top'
import Footer from '@/component/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <Navbar />
          <main className='min-h-screen'>{children}</main>
          <ScrollToTop />
          <Footer />
        </QueryProvider>
      </body>
    </html>
  )
}
